### ISSUE TITLE
Support helm chart dependencies

### ISSUE THREAD

**Issue by gxglls** [mittwald/go-helm-client#19]
go-helm-client are great to use ! but it does not seem to support helm's dependencies. When charts has dependencies, deployment errors will occur, my chart.yaml like:
```yaml
# ......
version: 0.1.0
appVersion: 0.1.2
dependencies:
- name: zookeeper-operator
  version: 0.2.8
  repository: https://charts.pravega.io
- name: hostpath-provisioner
  version: 0.5.1
  repository: http://iomesh.com/charts
# ......
```
